plugins {
    id 'java-library'
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

dependencies {
    implementation 'com.squareup:javapoet:1.13.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.google.testing.compile:compile-testing:0.23.0'
    testImplementation "com.google.dagger:hilt-core:$hiltVersion"
}

publishing {
    publications {
        compiler(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'localBuild'
            url = rootProject.layout.buildDirectory.dir('repo')
        }
    }
}
